config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#homepage'

  resources :stores do
    resources :items
  end

  resources :purchases do
    resources :orders
  end

  get 'history' => 'orders#history'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  # carrierwave settings
  mount_uploader :image, ItemImageUploader

  # relationships
  belongs_to :store
end

app/models/order.rb
class Order < ApplicationRecord
  # relationship
  belongs_to :user
  belongs_to :purchase
  has_many   :ordered_items
  has_many   :items, through: :ordered_items

  accepts_nested_attributes_for :ordered_items, allow_destroy: true

  def total
    self.ordered_items.map { |ordered_item|
      ordered_item.item.price * ordered_item.quantity
    }.sum
  end
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  # relationship
  belongs_to :order
  belongs_to :item
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  # relationship
  belongs_to :store
  belongs_to :user
  has_many   :orders
end

app/models/store.rb
class Store < ApplicationRecord
  # carreirwave settings
  mount_uploader :logo, LogoUploader
  mount_uploader :image, StoreImageUploader

  # relationships
  has_many :items
  has_many :purchases

  validates_presence_of :name, :phone, :address, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # relationship
  has_many :purchases
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_store
  before_action :set_item, only: [:edit, :update, :destroy]

  def create
    if @store.items.create item_params
      redirect_to store_path(@store)
    else
      render 'stores/show'
    end
  end

  def edit
  end

  def update
    if @item.update item_params
      redirect_to store_path(@store)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to store_path(@store)
  end

  private
  def item_params
    params.require(:item).permit(:name, :price, :image)
  end

  def set_store
    @store = Store.find params[:store_id]
  end

  def set_item
    @item = Item.find params[:id]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_purchase, except: :history

  def create
    @order      = @purchase.orders.build order_params
    @order.user = current_user

    if @order.save
      redirect_to purchase_path(@purchase)
    else
      render 'purchase/show'
    end
  end

  def update
    @order = Order.find params[:id]

    if @order.update order_params
      redirect_to purchase_path(@purchase)
    else
      render 'purchase/show'
    end
  end

  def history
    @orders = current_user.orders.includes(purchase: :store, ordered_items: :item)
  end

  private
  def set_purchase
    @purchase = Purchase.find params[:purchase_id]
  end

  def order_params
    params.require(:order).permit(
      ordered_items_attributes: [:id, :item_id, :quantity, :_destroy]
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  def index
    @purchases = Purchase.all
  end

  def show
    @purchase = Purchase.find params[:id]
    @order    = Order.find_by(user: current_user, purchase: @purchase) || Order.new
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = current_user.purchases.build purchase_params

    if @purchase.save
      redirect_to purchases_path
    else
      render 'new'
    end
  end

  private
  def purchase_params
    params.require(:purchase).permit(:time_period, :store_id, :end_time)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  def index
    @stores = Store.includes(:items)
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new store_params

    if @store.save
      redirect_to stores_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @store.update store_params
      redirect_to stores_path
    else
      render 'edit'
    end
  end

  def destroy
    @store.destroy

    redirect_to stores_path
  end

  private
  def store_params
    params.require(:store).permit(:name, :description, :address, :phone, :logo, :image)
  end

  def set_store
    @store = Store.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/application/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="columns">
      <div class="column is-2">
        <div class="footer-title">Buy Together</div>
      </div>
      <div class="column is-2">
        <ul class="footer-list">
          <li>歷史紀錄</li>
          <li>最近一星期</li>
          <li>最近一個月</li>
        </ul>
      </div>
      <div class="column is-2">
        <ul class="footer-list">
          <li>店家資訊</li>
          <li>新增店家</li>
          <li>店家一覽</li>
        </ul>
      </div>
      <div class="column is-2">
        <ul class="footer-list">
          <li>提案</li>
          <li>提案須知</li>
          <li>發起提案</li>
        </ul>
      </div>
      <div class="column is-2">
        <ul class="footer-list">
          <li>帳戶管理</li>
          <li>更新個人資訊</li>
        </ul>
      </div>
      <div class="column is-2">
        <ul class="footer-list">
          <li>聯絡我們</li>
          <li>Facebook</li>
          <li>Email</li>
          <li>Instagram</li>
        </ul>
      </div>
    </div>

    <p>
      © Copyright 2017 CodingAlpaca All Right Reserved
    </p>
  </div>
</footer>

app/views/application/_navbar.html.erb
<nav class="nav has-shadow">
  <div class="container">
    <div class="nav-left">
      <%= link_to root_path, class: 'nav-item' do %>
        <%= image_tag 'logo', alt: 'Buy Together Logo' %>
      <% end %>
    </div>
    <span class="nav-toggle">
      <span></span>
      <span></span>
      <span></span>
    </span>
    <div class="nav-right nav-menu">

      <!--  todo: 加上連結 -->
      <%= link_to '店家資訊', stores_path, class: 'nav-item is-tab is-active' %>
      <%= link_to '提議', new_purchase_path, class: 'nav-item is-tab' %>
      <%= link_to '歷史紀錄', history_path, class: 'nav-item is-tab' %>
      <%= link_to '帳戶管理', edit_user_registration_path, class: 'nav-item is-tab' %>

      <% if current_user %>
        <%= link_to '登出', destroy_user_session_path, method: :delete, class: 'nav-item is-tab' %>
      <% else %>
        <%= link_to '登入', new_user_session_path, class: 'nav-item is-tab' %>
      <% end %>

    </div>
  </div>
</nav>

app/views/items/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-6 is-offset-3">
        <div class="card">
          <div class="card-content">
            <h1 class="title is-5">更新菜單</h1>

            <%= form_for @item, url: store_item_path(@store, @item) do |f| %>
              <div class="field">
                <%= f.label :name, '名稱', class: 'label' %>
                <div class="control">
                  <%= f.text_field :name, class: 'input' %>
                </div>
              </div>

              <div class="field">
                <%= f.label :price, '價格', class: 'label' %>
                <div class="control">
                  <%= f.number_field :price, class: 'input' %>
                </div>
              </div>

              <div class="field">
                <%= f.label :image, '圖片', class: 'label' %>
                <div class="control">
                  <%= f.file_field :image, class: 'input' %>
                </div>
              </div>

              <div class="field">
                <%= link_to '刪除', store_item_path(@store, @item), method: :delete, data: { confirm: '確定嗎？'}, class: 'button is-danger' %>
                <%= f.submit '確定', class: 'button is-primary' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuyTogetherBase</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>

    <%= yield %>

    <%= render 'footer' %>
  </body>
</html>

app/views/orders/history.html.erb
<section class="section">
  <div class="container">
    <h1 class="title is-4">歷史紀錄</h1>

    <% @orders.each do |order| %>
      <h2 class="title is-6">
        訂購
        <%= order.purchase.store.name %>
        （<%= order.purchase.end_time.strftime('%m/%d %H:%M') %> 截止）
      </h2>

      <table class="table">
        <thead>
          <tr>
            <th>商品名稱</th>
            <th>價格</th>
            <th>數量</th>
          </tr>
        </thead>
        <tbody>
          <% order.ordered_items.each do |ordered_item| %>
            <tr>
              <td><%= ordered_item.item.name %></td>
              <td><%= ordered_item.item.price %></td>
              <td><%= ordered_item.quantity %></td>
            </tr>
          <% end %>

          <tr>
            <td class="title is-6 has-text-right" colspan="3">
              總共 <%= order.total %> 元
            </td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/pages/homepage.html.erb
<section class="section">
  <div class="container has-text-centered">
    <h1 class="title is-4">Welcome to BuyTogether!</h1>
    <h1 class="subtitle is-6">你可以在 <code>pages/homepage.html.erb</code> 找到這個頁面。</h1>
  </div>
</section>

app/views/purchases/_ordered_item_fields.html.erb
<div class="nested-fields">
  <div class="field is-horizontal">
    <div class="field-body">
      <div class="field">
        <div class="control">
          <span class="select">
            <%= f.collection_select :item_id, @purchase.store.items, :id, :name %>
          </span>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.number_field :quantity, class: 'input' %>
        </div>
      </div>
      <div class="field has-remove-button">
        <%= link_to_remove_association f, class: 'icon is-danger' do %>
          <i class="fa fa-times"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/purchases/index.html.erb
<section class="section purchases-section">
  <div class="container">
    <h1 class="title is-4">所有團購</h1>

    <div class="columns is-multiline">
      <% @purchases.each do |purchase| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-2by1">
                <%= image_tag purchase.store.image %>
              </figure>
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                    <figure class="image is-48x48">
                      <%= image_tag purchase.store.logo %>
                    </figure>
                  </div>
                  <div class="media-content">
                    <%= link_to purchase_path(purchase) do %>
                      <p class="title is-4"><%= purchase.store.name %></p>
                    <% end %>
                    <p class="subtitle is-6"><%= purchase.user.email %></p>
                  </div>
                </div>
                <div class="content">
                  <%= truncate purchase.store.description, length: 30 %>
                </div>
                <div class="columns">
                  <div class="column is-3">
                    <div class="title is-4">$150</div>
                    <div class="subtitle is-6">最低價</div>
                  </div>
                  <div class="column is-3">
                    <div class="title is-4">140</div>
                    <div class="subtitle is-6">人團購</div>
                  </div>
                  <div class="column is-6">
                    <div class="title is-4"><%= purchase.end_time.strftime('%m/%d %H:%M') %></div>
                    <div class="subtitle is-6">限時截止</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/purchases/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title is-4">提議</h1>

    <div class="columns">
      <div class="column is-5">
        <div class="box">
          <%= form_for @purchase do |f| %>
            <div class="field">
              <%= f.label :time_period, '時段', class: 'label' %>

              <div class="control">
                <span class="select">
                  <%= f.select :time_period, ['早餐', '午餐', '晚餐'] %>
                </span>
              </div>
            </div>

            <div class="field">
              <%= f.label :store_id, '餐廳', class: 'label' %>

              <div class="control">
                <span class="select">
                  <%= f.collection_select :store_id, Store.all, :id, :name %>
                </span>
              </div>
            </div>

            <div class="field">
              <%= f.label :end_time, '截止日期', class: 'label' %>

              <div class="control">
                <%= f.datetime_select :end_time %>
              </div>
            </div>

            <div class="field">
              <%= f.submit '確定', class: 'button is-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/purchases/show.html.erb
<section class="section store-image-section">
  <div class="container">
    <figure class="image">
      <%= image_tag @purchase.store.image, class: 'store-picture' %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <%= image_tag @purchase.store.logo %>
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= @purchase.store.name %></p>
              <p class="subtitle is-6"><%= @purchase.user.email %></p>
            </div>
          </div>
          <div class="content has-description">
            <%= truncate @purchase.store.description, length: 35 %>
          </div>
          <div class="content">
            地址：<%= @purchase.store.address %><br>
            電話：<%= @purchase.store.phone %>
          </div>
        </div>
      </div>
    </figure>
  </div>
</section>

<section class="section items-section">
  <div class="container">
    <div class="columns">
      <div class="column is-7">
        <div class="columns is-multiline">
          <% @purchase.store.items.each do |item| %>
            <div class="column is-4">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-2by1">
                    <%= image_tag item.image %>
                  </figure>
                </div>
                <div class="card-content">
                  <div><%= item.name %></div>
                  <div class="title is-4">$<%= item.price %></div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="column is-5">
        <div class="card">
          <div class="card-content">
            <h1 class="title is-5">購物列表</h1>

            <%= form_for [@purchase, @order] do |f| %>

              <%= f.fields_for :ordered_items do |item_form| %>
                <%= render 'ordered_item_fields', f: item_form %>
              <% end %>

              <div class="field">
                <%= link_to_add_association '新增商品', f, :ordered_items, class: 'button is-success is-outlined' %>
              </div>

              <div class="field">
                <input type="submit" value="確定" class="button is-primary is-medium is-fullwidth">
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/stores/_form.html.erb
<%= form_for @store do |f| %>
  <div class="columns">
    <div class="column is-7">
      <div class="field">
        <%= f.label :logo, '商標', class: 'label' %>
        <%= f.file_field :logo %>
      </div>
      <div class="field">
        <%= f.label :image, '圖片', class: 'label' %>
        <%= f.file_field :image %>
      </div>
    </div>
    <div class="column is-5">
      <div class="field">
        <%= f.label :name, '名稱', class: 'label' %>
        <div class="control">
          <%= f.text_field :name, class: 'input' %>
          <% @store.errors.full_messages_for(:name).each do |msg| %>
            <p class="help is-danger"><%= msg %></p>
          <% end %>
        </div>
      </div>
      <div class="field">
        <%= f.label :address, '地址', class: 'label' %>
        <div class="control">
          <%= f.text_field :address, class: 'input' %>
          <% @store.errors.full_messages_for(:address).each do |msg| %>
            <p class="help is-danger"><%= msg %></p>
          <% end %>
        </div>
      </div>
      <div class="field">
        <%= f.label :phone, '電話', class: 'label' %>
        <div class="control">
          <%= f.text_field :phone, class: 'input' %>
          <% @store.errors.full_messages_for(:phone).each do |msg| %>
            <p class="help is-danger"><%= msg %></p>
          <% end %>
        </div>
      </div>
      <div class="field">
        <%= f.label :description, '簡短敘述', class: 'label' %>
        <div class="control">
          <%= f.text_area :description, class: 'textarea' %>
          <% @store.errors.full_messages_for(:description).each do |msg| %>
            <p class="help is-danger"><%= msg %></p>
          <% end %>
        </div>
      </div>
      <div class="field">
        <%= f.submit 'submit', class: 'button is-primary is-medium is-fullwidth' %>
      </div>
    </div>
  </div>
<% end %>

app/views/stores/edit.html.erb
<section class="section store-form-section">
  <div class="container">
    <h1 class="title is-4">更新店家</h1>
    <div class="box">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/stores/index.html.erb
<% @stores.each do |store| %>
  <section class="section store-section">
    <div class="container">
      <div class="card has-store">
        <div class="store-info">
          <%= link_to store_path(store) do %>
            <figure class="image is-3by2">
              <%= image_tag store.image %>
            </figure>
          <% end %>
          <div class="card-content has-border-right">
            <%= link_to edit_store_path(store),
                        class: 'button is-small is-primary is-outlined is-edit' do %>
              <i class="fa fa-pencil-square-o"></i>
            <% end %>
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <%= image_tag store.logo %>
                </figure>
              </div>
              <div class="media-content">
                <%= link_to store_path(store) do %>
                  <p class="title is-4"><%= store.name %></p>
                <% end %>
                <p class="subtitle is-6">@johnsmith</p>
              </div>
            </div>
            <div class="content has-description">
              <%= truncate store.description, length: 150 %>
            </div>
            <div class="content has-address">
              地址：<%= store.address %>
            </div>
            <div class="columns">
              <div class="column is-3">
                <div class="title is-4">$150</div>
                <div class="subtitle">最低價</div>
              </div>
              <div class="column is-3">
                <div class="title is-4">15</div>
                <div class="subtitle">項商品</div>
              </div>
              <div class="column is-6">
                <div class="title is-4"><%= store.phone %></div>
                <div class="subtitle">聯絡電話</div>
              </div>
            </div>
          </div>
        </div>
        <div class="store-menu">
          <div class="titlebar has-text-centered">Menu</div>

          <div class="card-content">
            <div class="columns is-multiline">
              <% store.items.each do |item| %>
                <div class="column is-4">
                  <div class="card">
                    <div class="card-image">
                      <figure class="image is-4by3">
                        <%= image_tag item.image %>
                      </figure>
                    </div>
                    <div class="card-content">
                      <div><%= item.name %></div>
                      <div class="title is-5">$<%= item.price %></div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/stores/new.html.erb
<section class="section store-form-section">
  <div class="container">
    <h1 class="title is-4">新增店家</h1>
    <div class="box">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/stores/show.html.erb
<section class="section store-image-section">
  <div class="container">
    <figure class="image">
      <%= image_tag @store.image, class: 'store-picture' %>
        <div class="card">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <%= image_tag @store.logo %>
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4"><%= @store.name %></p>
                <p class="subtitle is-6">@johnsmith</p>
              </div>
            </div>
            <div class="content has-description">
              <%= truncate @store.description, length: 100 %>
            </div>
            <div class="content">
              地址：<%= @store.address %><br>
              電話：<%= @store.phone %>
            </div>
          </div>
          <div class="card-footer">
            <div class="card-footer-item">
              <%= link_to 'edit', edit_store_path(@store) %>
            </div>
            <div class="card-footer-item">
              <%= link_to 'delete', store_path(@store), method: :delete, data: { confirm: '確定要刪除嗎？' } %>
            </div>
          </div>
        </div>
    </figure>
  </div>
</section>

<section class="section items-section">
  <div class="container">
    <div class="columns">
      <div class="column is-7">
        <div class="columns is-multiline">
          <% @store.items.each do |item| %>
            <div class="column is-4">
              <div class="card">
                <div class="card-image">
                  <%= link_to edit_store_item_path(@store, item) do %>
                    <figure class="image is-2by1">
                      <%= image_tag item.image %>
                    </figure>
                  <% end %>
                </div>
                <div class="card-content">
                  <div><%= item.name %></div>
                  <div class="title is-4">$<%= item.price %></div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="column is-5">
        <div class="card">
          <div class="card-content">
            <h1 class="title is-5">新增菜單</h1>

            <%= form_for Item.new, url: store_items_path(@store) do |f| %>
              <div class="field">
                <%= f.label :name, '名稱', class: 'label' %>
                <div class="control">
                  <%= f.text_field :name, class: 'input' %>
                </div>
              </div>

              <div class="field">
                <%= f.label :price, '價格', class: 'label' %>
                <div class="control">
                  <%= f.number_field :price, class: 'input' %>
                </div>
              </div>

              <div class="field">
                <%= f.label :image, '圖片', class: 'label' %>
                <div class="control">
                  <%= f.file_field :image, class: 'input' %>
                </div>
              </div>

              <div class="field">
                <%= f.submit '確定', class: 'button is-primary is-medium is-fullwidth' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'button is-link' %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'button is-link' %>
<% end -%>